function signal = SimSignalOFDM(Fc, BW, P_Watt, F_sample, Count_sample)
    % Fc - несущая; BW - полоса в МГЦ; P_Watt - мощность сигнала в Вт
    % F_sample - частота дискретизации; Count_sample - кол-во отсчетов
    
    % Параметры из 3GPP
    LTE_BW =   [1.4 3  5  10 15 20];
    LIE_N_RB = [6   15 25 50 75 100];
    SCS = 15; % kHz

    % Проверка
    id_BW = find(LTE_BW == BW);
    if isempty(id_BW)
        error('Bandwidth не подходит');
    end

    if Fc < 1e6
        % error('Частота Fc меньше 1е6');
        disp('Fc меньше 1e6');
        SCS = SCS/1000;
    end
 
    

    % Тело функции
    % Analysis of passive intermodulation generated by broadband signals 
    % ELECTRONICS LETTERS 1st April 2016 Vol. 52 No. 7 pp. 564–566
    T_sample = 1/F_sample;
    num_sample = 0:Count_sample-1;
    time_sample = num_sample * T_sample;
    N_RB = LIE_N_RB(id_BW);
    Vol = sqrt(P_Watt .* 50) * sqrt(2);
    y = 0;
    for i = 1:N_RB
        freq = Fc + (i - 1) * SCS*1000;
        y = y + Vol/N_RB * cos(2*pi * freq * time_sample);
    end
    signal = y;
end